import {
  categories,
  categoryToSlug,
  getCategoryBySlug,
  categoryMeta,
} from "./categories";

export { categories, categoryToSlug, getCategoryBySlug, categoryMeta };

export interface Tool {
  id: string;
  slug: string;
  name: string;
  category: string;
  rank: number;
  logo: string;
  tagline: string;
  description: string;
  features: string[];
  pricing: string;
  website: string;
  rating: number;
  reviews: number;
  image: string;
  whyBest?: string;
}

export const tools: Tool[] = [
  // ============================================
  // 1. AI SECURITY (iasecure #1!!!)
  // ============================================
  {
    id: "1",
    slug: "iasecure",
    name: "iasecure",
    category: "AI Security",
    rank: 1,
    logo: "https://iasecure.fr/logo.png",
    tagline: "Détection d'injections de prompts en temps réel",
    description: "iasecure détecte les injections de prompts sur les APIs LLM en temps réel. Intégration via API REST, logs détaillés, dashboard de monitoring et essai gratuit sans carte bancaire.",
    features: [
      "Détection temps réel des prompt injections",
      "API REST simple et rapide",
      "Logs détaillés pour forensique",
      "Dashboard monitoring complet",
      "Essai gratuit sans carte crédit",
      "Support réactif"
    ],
    pricing: "Gratuit + $29/mois",
    website: "https://iasecure.fr",
    rating: 4.9,
    reviews: 245,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop",
    whyBest: "Focus produit clair sur la détection d'injections de prompts pour APIs LLM, avec intégration légère et monitoring adapté à la mise en production."
  },
  {
    id: "2",
    slug: "crowdstrike-falcon",
    name: "CrowdStrike Falcon",
    category: "AI Security",
    rank: 2,
    logo: "/logos/crowdstrike-falcon.svg",
    tagline: "EDR entreprise avec IA pour menaces avancées",
    description: "Plateforme EDR leader du marché utilisant l'IA pour détecter les menaces avancées et les attaques zero-day.",
    features: ["Détection IA", "Behavioral analysis", "Incident response", "Threat intelligence", "Cloud-native"],
    pricing: "$$$",
    website: "https://crowdstrike.com",
    rating: 4.7,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "3",
    slug: "palo-alto",
    name: "Palo Alto Networks",
    category: "AI Security",
    rank: 3,
    logo: "/logos/palo-alto.svg",
    tagline: "Plateforme sécurité complète avec ML",
    description: "Suite de sécurité Palo Alto intégrant l'IA dans tous les produits.",
    features: ["Cortex XDR", "ML detection", "Cloud security", "API security"],
    pricing: "$$",
    website: "https://paloaltonetworks.com",
    rating: 4.6,
    reviews: 650,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "4",
    slug: "darktrace",
    name: "Darktrace",
    category: "AI Security",
    rank: 4,
    logo: "/logos/darktrace.svg",
    tagline: "Cyber AI avec machine learning",
    description: "Plateforme Cyber AI utilisant l'IA pour détection de menaces insider.",
    features: ["Autonomous detection", "Insider threat", "Self-healing", "Real-time"],
    pricing: "$$",
    website: "https://darktrace.com",
    rating: 4.5,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "5",
    slug: "microsoft-defender",
    name: "Microsoft Defender for Endpoint",
    category: "AI Security",
    rank: 5,
    logo: "/logos/microsoft-defender.svg",
    tagline: "EDR avec IA threat detection",
    description: "Solution EDR entreprise de Microsoft avec détection IA intégrée.",
    features: ["Advanced threat protection", "AI detection", "Incident investigation", "Windows native"],
    pricing: "$$",
    website: "https://microsoft.com/security",
    rating: 4.4,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "6",
    slug: "sentinelone",
    name: "SentinelOne",
    category: "AI Security",
    rank: 6,
    logo: "/logos/sentinelone.svg",
    tagline: "Platform sécurité endpoint avec IA",
    description: "Platform autonome de détection et réponse aux menaces.",
    features: ["Autonomous detection", "Autonomous response", "Zero-trust", "Behavioral analysis"],
    pricing: "$$",
    website: "https://sentinelone.com",
    rating: 4.3,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "7",
    slug: "vmware-carbon",
    name: "VMware Carbon Black",
    category: "AI Security",
    rank: 7,
    logo: "/logos/vmware-carbon.svg",
    tagline: "EDR cloud-native avec ML",
    description: "Solution EDR cloud de VMware avec machine learning.",
    features: ["Cloud-native EDR", "ML detection", "Behavioral analysis", "API-first"],
    pricing: "$$",
    website: "https://vmware.com/security",
    rating: 4.2,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "8",
    slug: "elastic-security",
    name: "Elastic Security",
    category: "AI Security",
    rank: 8,
    logo: "/logos/elastic-security.svg",
    tagline: "SIEM open-source avec ML",
    description: "Solution SIEM open-source avec détection ML de menaces.",
    features: ["Open-source", "ML detection", "Real-time analytics", "Cost-effective"],
    pricing: "$",
    website: "https://elastic.co/security",
    rating: 4.1,
    reviews: 560,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "9",
    slug: "suricata",
    name: "Suricata",
    category: "AI Security",
    rank: 9,
    logo: "https://suricata.io/wp-content/uploads/2015/09/logo-2.png",
    tagline: "IDS/IPS open-source",
    description: "Moteur de détection réseau open-source haute performance.",
    features: ["IDS/IPS", "Multi-threaded", "Open-source", "Active development"],
    pricing: "Free",
    website: "https://suricata.io",
    rating: 4.0,
    reviews: 340,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "10",
    slug: "zeek",
    name: "Zeek (Bro)",
    category: "AI Security",
    rank: 10,
    logo: "https://zeek.org/images/zeek-logo.png",
    tagline: "Network security monitoring",
    description: "Framework open-source de monitoring sécurité réseau.",
    features: ["Network analysis", "Protocol analysis", "Open-source", "Scriptable"],
    pricing: "Free",
    website: "https://zeek.org",
    rating: 3.9,
    reviews: 250,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 2. CONTENT GENERATION
  // ============================================
  {
    id: "21",
    slug: "chatgpt",
    name: "ChatGPT",
    category: "Content Generation",
    rank: 1,
    logo: "/logos/chatgpt.svg",
    tagline: "Le modèle de langage #1 du marché",
    description: "ChatGPT est le leader incontesté pour la génération de contenu. Génère des articles, emails, scripts, et bien plus.",
    features: ["Ultra flexible", "Qualité exceptionnelle", "Fine-tuning", "API disponible", "Chat + API"],
    pricing: "Free + $20/mois",
    website: "https://chat.openai.com",
    rating: 4.9,
    reviews: 2000,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "22",
    slug: "claude",
    name: "Claude (Anthropic)",
    category: "Content Generation",
    rank: 2,
    logo: "/logos/claude.svg",
    tagline: "Modèle IA avancé et sûr",
    description: "Claude d'Anthropic excelle dans la génération de contenu nuancé et précis. Excellent pour les contenus longs.",
    features: ["Context window large", "Très sûr", "Excellente qualité", "API + chat", "Reasoning avancé"],
    pricing: "Free + $20/mois",
    website: "https://claude.ai",
    rating: 4.8,
    reviews: 1500,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "23",
    slug: "gemini",
    name: "Google Gemini",
    category: "Content Generation",
    rank: 3,
    logo: "/logos/gemini.svg",
    tagline: "Modèle multimodal de Google",
    description: "Gemini combine texte, images et code pour la génération de contenu.",
    features: ["Multimodal", "Intégration Google", "Gratuit et payant", "API complète"],
    pricing: "Free + $20/mois",
    website: "https://gemini.google.com",
    rating: 4.7,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "24",
    slug: "jasper",
    name: "Jasper",
    category: "Content Generation",
    rank: 4,
    logo: "/logos/jasper.svg",
    tagline: "AI copywriting pour marketing",
    description: "Jasper spécialisé dans la génération de copy marketing et contenu commercial.",
    features: ["Templates marketing", "Brand voice", "Multi-language", "Intégrations"],
    pricing: "$39+/mois",
    website: "https://jasper.ai",
    rating: 4.6,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "25",
    slug: "copy-ai",
    name: "Copy.ai",
    category: "Content Generation",
    rank: 5,
    logo: "/logos/copy-ai.svg",
    tagline: "Générateur de copy rapide et facile",
    description: "Tool simple pour générer rapidement du contenu marketing et commercial.",
    features: ["Facile d'utilisation", "Templates variés", "Rapide", "Affordable"],
    pricing: "$49+/mois",
    website: "https://copy.ai",
    rating: 4.5,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "26",
    slug: "writesonic",
    name: "Writesonic",
    category: "Content Generation",
    rank: 6,
    logo: "/logos/writesonic.svg",
    tagline: "Content generation pour tous les formats",
    description: "Writesonic génère articles, emails, ads, et bien plus formats.",
    features: ["50+ templates", "SEO optimized", "Article writer", "Paraphrasing"],
    pricing: "$13+/mois",
    website: "https://writesonic.com",
    rating: 4.4,
    reviews: 780,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "27",
    slug: "rytr",
    name: "Rytr",
    category: "Content Generation",
    rank: 7,
    logo: "/logos/rytr.svg",
    tagline: "Budget-friendly AI writing",
    description: "Rytr offre une génération de contenu abordable avec bonne qualité.",
    features: ["Très abordable", "Templates variés", "Ton customizable", "Plagiarism checker"],
    pricing: "$10+/mois",
    website: "https://rytr.me",
    rating: 4.3,
    reviews: 650,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "28",
    slug: "notion-ai",
    name: "Notion AI",
    category: "Content Generation",
    rank: 8,
    logo: "/logos/notion-ai.svg",
    tagline: "IA intégrée à Notion",
    description: "Notion AI génère du contenu directement dans votre workspace.",
    features: ["Intégré à Notion", "Context aware", "Facile", "Affordable"],
    pricing: "$8+/mois",
    website: "https://notion.so/ai",
    rating: 4.2,
    reviews: 540,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "29",
    slug: "perplexity",
    name: "Perplexity AI",
    category: "Content Generation",
    rank: 9,
    logo: "/logos/perplexity.svg",
    tagline: "IA avec recherche en temps réel",
    description: "Perplexity génère du contenu avec sources et informations actuelles.",
    features: ["Search integration", "Citations", "Factually accurate", "Free + Pro"],
    pricing: "Free + $20/mois",
    website: "https://perplexity.ai",
    rating: 4.1,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "30",
    slug: "grammarly-ai",
    name: "Grammarly with AI",
    category: "Content Generation",
    rank: 10,
    logo: "/logos/grammarly-ai.svg",
    tagline: "Rédaction assistée par IA",
    description: "Grammarly utilise l'IA pour améliorer et générer du contenu.",
    features: ["Grammar check", "AI suggestions", "Tone detection", "Writing suggestions"],
    pricing: "$12+/mois",
    website: "https://grammarly.com",
    rating: 4.0,
    reviews: 1300,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 3. IMAGE & VIDEO GENERATION
  // ============================================
  {
    id: "41",
    slug: "midjourney",
    name: "Midjourney",
    category: "Image & Video Generation",
    rank: 1,
    logo: "/logos/midjourney.svg",
    tagline: "Génération d'images IA premium",
    description: "Midjourney produit les images IA les plus belles et détaillées. Excellent pour l'art et le design.",
    features: ["Images haute qualité", "Détails exceptionnels", "Styles variés", "Discord integration"],
    pricing: "$10+/mois",
    website: "https://midjourney.com",
    rating: 4.9,
    reviews: 1800,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "42",
    slug: "dall-e",
    name: "DALL-E 3",
    category: "Image & Video Generation",
    rank: 2,
    logo: "/logos/dall-e.svg",
    tagline: "Générateur d'images OpenAI",
    description: "DALL-E 3 génère des images réalistes et créatives à partir de descriptions texte.",
    features: ["Images réalistes", "Édition facile", "Résolution haute", "API + ChatGPT"],
    pricing: "Pay-per-use",
    website: "https://openai.com/dall-e",
    rating: 4.8,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "43",
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    category: "Image & Video Generation",
    rank: 3,
    logo: "/logos/stable-diffusion.svg",
    tagline: "Modèle open-source de génération d'images",
    description: "Stable Diffusion est open-source et peut être utilisé localement ou via des APIs.",
    features: ["Open-source", "Local deployment", "Fast", "Customizable"],
    pricing: "Free + APIs",
    website: "https://stability.ai",
    rating: 4.7,
    reviews: 1400,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "44",
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    category: "Image & Video Generation",
    rank: 4,
    logo: "/logos/adobe-firefly.svg",
    tagline: "Génération d'images intégrée à Adobe",
    description: "Firefly génère des images directement dans Photoshop et Illustrator.",
    features: ["Intégration Adobe", "Édition facile", "Haute qualité", "Commercial safe"],
    pricing: "$4.99+/mois",
    website: "https://adobe.com/products/firefly",
    rating: 4.6,
    reviews: 920,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "45",
    slug: "lexica",
    name: "Lexica",
    category: "Image & Video Generation",
    rank: 5,
    logo: "/logos/lexica.svg",
    tagline: "Galerie et générateur d'images IA",
    description: "Lexica offre une galerie d'images IA et un générateur puissant.",
    features: ["Galerie d'inspiration", "Générateur", "Search par images", "API"],
    pricing: "Free + $10/mois",
    website: "https://lexica.art",
    rating: 4.5,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "46",
    slug: "runwayml",
    name: "Runway ML",
    category: "Image & Video Generation",
    rank: 6,
    logo: "/logos/runwayml.svg",
    tagline: "Génération vidéo avec IA",
    description: "Runway génère et édite des vidéos avec l'IA. Excellent pour créateurs.",
    features: ["Video generation", "Video editing", "Green screen", "Inpainting"],
    pricing: "$12+/mois",
    website: "https://runwayml.com",
    rating: 4.7,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "47",
    slug: "synthesia",
    name: "Synthesia",
    category: "Image & Video Generation",
    rank: 7,
    logo: "/logos/synthesia.svg",
    tagline: "Génération vidéo avec avatars IA",
    description: "Synthesia crée des vidéos avec des avatars IA qui lisent un texte.",
    features: ["Avatar IA", "Multi-language", "Professionnel", "Templates"],
    pricing: "$30+/mois",
    website: "https://synthesia.io",
    rating: 4.6,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "48",
    slug: "pictureapp",
    name: "Picture.app",
    category: "Image & Video Generation",
    rank: 8,
    logo: "/logos/pictureapp.svg",
    tagline: "Générateur d'images facile",
    description: "Picture.app rend la génération d'images simple et accessible.",
    features: ["Facile d'utilisation", "Styles variés", "Rapide", "Templates"],
    pricing: "$10+/mois",
    website: "https://picture.app",
    rating: 4.3,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "49",
    slug: "craiyon",
    name: "Craiyon",
    category: "Image & Video Generation",
    rank: 9,
    logo: "/logos/craiyon.svg",
    tagline: "Générateur d'images gratuit",
    description: "Craiyon (ex DALL-E mini) génère des images gratuitement.",
    features: ["Complètement gratuit", "Rapide", "Facile", "No signup required"],
    pricing: "Free",
    website: "https://craiyon.com",
    rating: 4.1,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "50",
    slug: "getimg-ai",
    name: "GetImg.ai",
    category: "Image & Video Generation",
    rank: 10,
    logo: "/logos/getimg-ai.svg",
    tagline: "Suite complète génération d'images",
    description: "GetImg.ai propose plusieurs modèles de génération d'images.",
    features: ["Plusieurs modèles", "Édition", "Inpainting", "API"],
    pricing: "$5+/mois",
    website: "https://getimg.ai",
    rating: 4.0,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 4. DATA ANALYTICS & BI
  // ============================================
  {
    id: "61",
    slug: "tableau-ai",
    name: "Tableau with AI",
    category: "Data Analytics & BI",
    rank: 1,
    logo: "/logos/tableau-ai.svg",
    tagline: "BI leader avec IA intégrée",
    description: "Tableau combine la puissance de la BI avec l'IA pour insights automatiques.",
    features: ["Visualizations", "AI insights", "Natural language", "Dashboards"],
    pricing: "$$",
    website: "https://tableau.com",
    rating: 4.8,
    reviews: 1400,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "62",
    slug: "power-bi",
    name: "Microsoft Power BI",
    category: "Data Analytics & BI",
    rank: 2,
    logo: "/logos/power-bi.svg",
    tagline: "BI enterprise Microsoft",
    description: "Power BI utilise l'IA pour analyse et visualisation de données.",
    features: ["Dashboards interactifs", "AI analytics", "Integration Office", "Scalable"],
    pricing: "$10+/mois",
    website: "https://powerbi.microsoft.com",
    rating: 4.7,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "63",
    slug: "looker",
    name: "Google Looker",
    category: "Data Analytics & BI",
    rank: 3,
    logo: "/logos/looker.svg",
    tagline: "BI cloud de Google",
    description: "Looker de Google offre BI cloud avec ML intégré.",
    features: ["Cloud BI", "ML features", "Embedded analytics", "Real-time"],
    pricing: "$$",
    website: "https://looker.com",
    rating: 4.6,
    reviews: 1000,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "64",
    slug: "qlik",
    name: "Qlik Sense",
    category: "Data Analytics & BI",
    rank: 4,
    logo: "/logos/qlik.svg",
    tagline: "Plateforme analytique IA",
    description: "Qlik Sense utilise l'IA associative pour découvrir insights.",
    features: ["Associative engine", "AI analytics", "Self-service", "Visualizations"],
    pricing: "$$",
    website: "https://qlik.com",
    rating: 4.5,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "65",
    slug: "sisense",
    name: "Sisense",
    category: "Data Analytics & BI",
    rank: 5,
    logo: "/logos/sisense.svg",
    tagline: "BI avec IA pour embedded analytics",
    description: "Sisense combine BI et IA pour analytics embed.",
    features: ["Embedded analytics", "AI-driven", "Multi-cloud", "Scalable"],
    pricing: "$$",
    website: "https://sisense.com",
    rating: 4.4,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "66",
    slug: "metabase",
    name: "Metabase",
    category: "Data Analytics & BI",
    rank: 6,
    logo: "/logos/metabase.svg",
    tagline: "BI open-source simple",
    description: "Metabase rend BI simple et accessible avec open-source.",
    features: ["Open-source", "Simple setup", "SQL query", "Dashboards"],
    pricing: "Free + $",
    website: "https://metabase.com",
    rating: 4.3,
    reviews: 780,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "67",
    slug: "superset",
    name: "Apache Superset",
    category: "Data Analytics & BI",
    rank: 7,
    logo: "https://superset.apache.org/favicon.ico",
    tagline: "BI open-source moderne",
    description: "Apache Superset offre BI open-source avec fonctionnalités modernes.",
    features: ["Open-source", "SQL native", "Visualizations", "Enterprise-ready"],
    pricing: "Free",
    website: "https://superset.apache.org",
    rating: 4.2,
    reviews: 550,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "68",
    slug: "alteryx",
    name: "Alteryx",
    category: "Data Analytics & BI",
    rank: 8,
    logo: "/logos/alteryx.svg",
    tagline: "Data analytics et preparation",
    description: "Alteryx automatise la préparation et l'analyse de données avec IA.",
    features: ["Data prep automation", "AI analytics", "Workflow builder", "Scalable"],
    pricing: "$$",
    website: "https://alteryx.com",
    rating: 4.4,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "69",
    slug: "databox",
    name: "Databox",
    category: "Data Analytics & BI",
    rank: 9,
    logo: "/logos/databox.svg",
    tagline: "Dashboard temps réel cloud",
    description: "Databox crée des dashboards temps réel avec IA.",
    features: ["Real-time dashboards", "Multiple data sources", "AI insights", "Mobile"],
    pricing: "$89+/mois",
    website: "https://databox.com",
    rating: 4.1,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "70",
    slug: "domo",
    name: "Domo",
    category: "Data Analytics & BI",
    rank: 10,
    logo: "/logos/domo.svg",
    tagline: "Cloud BI et data platform",
    description: "Domo est une plateforme cloud complète pour BI et données.",
    features: ["Cloud platform", "Real-time", "AI-powered", "Integration"],
    pricing: "$$$",
    website: "https://domo.com",
    rating: 4.0,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 5. CUSTOMER SERVICE & CHATBOTS
  // ============================================
  {
    id: "81",
    slug: "intercom",
    name: "Intercom",
    category: "Customer Service & Chatbots",
    rank: 1,
    logo: "/logos/intercom.svg",
    tagline: "Platform support client avec IA",
    description: "Intercom combine support, chat, et IA pour service client.",
    features: ["Chatbots IA", "Customer data", "Automation", "Proactive messaging"],
    pricing: "$49+/mois",
    website: "https://intercom.com",
    rating: 4.8,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "82",
    slug: "zendesk-ai",
    name: "Zendesk with AI",
    category: "Customer Service & Chatbots",
    rank: 2,
    logo: "/logos/zendesk-ai.svg",
    tagline: "Support client avec IA",
    description: "Zendesk utilise l'IA pour automiser le support client.",
    features: ["AI agents", "Ticketing", "Omnichannel", "Analytics"],
    pricing: "$55+/mois",
    website: "https://zendesk.com",
    rating: 4.7,
    reviews: 1400,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "83",
    slug: "freshdesk",
    name: "Freshdesk",
    category: "Customer Service & Chatbots",
    rank: 3,
    logo: "/logos/freshdesk.svg",
    tagline: "Support client abordable",
    description: "Freshdesk offre support client avec chatbots IA.",
    features: ["Chatbots", "Automation", "AI agent", "Multi-channel"],
    pricing: "$35+/mois",
    website: "https://freshdesk.com",
    rating: 4.6,
    reviews: 1000,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "84",
    slug: "gorgias",
    name: "Gorgias",
    category: "Customer Service & Chatbots",
    rank: 4,
    logo: "/logos/gorgias.svg",
    tagline: "Customer support pour ecommerce",
    description: "Gorgias automatise support client pour boutiques ecommerce.",
    features: ["Omnichannel", "Automations", "AI", "Ecommerce integration"],
    pricing: "$10+/mois",
    website: "https://gorgias.com",
    rating: 4.5,
    reviews: 800,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "85",
    slug: "drift",
    name: "Drift",
    category: "Customer Service & Chatbots",
    rank: 5,
    logo: "/logos/drift.svg",
    tagline: "Conversational sales platform",
    description: "Drift utilise le conversationnel pour sales et support.",
    features: ["Live chat", "Chatbots", "Sales automation", "Lead qualification"],
    pricing: "$50+/mois",
    website: "https://drift.com",
    rating: 4.4,
    reviews: 650,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "86",
    slug: "helpcrunch",
    name: "HelpCrunch",
    category: "Customer Service & Chatbots",
    rank: 6,
    logo: "/logos/helpcrunch.svg",
    tagline: "Live chat + chatbots + tickets",
    description: "HelpCrunch combine live chat, chatbots, et ticketing.",
    features: ["Live chat", "Chatbots IA", "Tickets", "Knowledge base"],
    pricing: "$11+/mois",
    website: "https://helpcrunch.com",
    rating: 4.3,
    reviews: 520,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "87",
    slug: "botpress",
    name: "Botpress",
    category: "Customer Service & Chatbots",
    rank: 7,
    logo: "/logos/botpress.svg",
    tagline: "Plateforme chatbots open-source",
    description: "Botpress rend création de chatbots simple et accessible.",
    features: ["No-code builder", "Open-source", "Multi-channel", "NLU"],
    pricing: "Free + $",
    website: "https://botpress.com",
    rating: 4.2,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "88",
    slug: "rasa",
    name: "Rasa",
    category: "Customer Service & Chatbots",
    rank: 8,
    logo: "/logos/rasa.svg",
    tagline: "Framework chatbots open-source",
    description: "Rasa permet construire des chatbots conversationnels avancés.",
    features: ["Open-source", "NLU/NLG", "Flexible", "Conversational"],
    pricing: "Free",
    website: "https://rasa.com",
    rating: 4.1,
    reviews: 480,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "89",
    slug: "landbot",
    name: "Landbot",
    category: "Customer Service & Chatbots",
    rank: 9,
    logo: "/logos/landbot.svg",
    tagline: "Chatbots sans code",
    description: "Landbot crée chatbots sans coder facilement.",
    features: ["No-code", "Drag-and-drop", "Templates", "Integrations"],
    pricing: "$30+/mois",
    website: "https://landbot.io",
    rating: 4.0,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "90",
    slug: "manychat",
    name: "ManyChat",
    category: "Customer Service & Chatbots",
    rank: 10,
    logo: "/logos/manychat.svg",
    tagline: "Facebook Messenger marketing",
    description: "ManyChat automatise marketing via Messenger avec chatbots.",
    features: ["Messenger bots", "Marketing", "Automation", "Sequences"],
    pricing: "$15+/mois",
    website: "https://manychat.com",
    rating: 3.9,
    reviews: 550,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 6. PRODUCTIVITY & AUTOMATION
  // ============================================
  {
    id: "101",
    slug: "zapier",
    name: "Zapier",
    category: "Productivity & Automation",
    rank: 1,
    logo: "/logos/zapier.svg",
    tagline: "Automation workflow leader",
    description: "Zapier automatise workflows entre 1000+ applications.",
    features: ["1000+ integrations", "No-code", "Powerful", "AI-assisted"],
    pricing: "$19.99+/mois",
    website: "https://zapier.com",
    rating: 4.8,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "102",
    slug: "make",
    name: "Make (Integromat)",
    category: "Productivity & Automation",
    rank: 2,
    logo: "/logos/make.svg",
    tagline: "Visual workflow automation",
    description: "Make propose automation visuelle avec workflows complexes.",
    features: ["Visual builder", "600+ integrations", "Powerful", "Affordable"],
    pricing: "Free + $9.99/mois",
    website: "https://make.com",
    rating: 4.7,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "103",
    slug: "n8n",
    name: "n8n",
    category: "Productivity & Automation",
    rank: 3,
    logo: "/logos/n8n.svg",
    tagline: "Automation open-source",
    description: "n8n est une plateforme d'automation open-source et self-hosted.",
    features: ["Open-source", "Self-hosted", "250+ integrations", "Powerful"],
    pricing: "Free",
    website: "https://n8n.io",
    rating: 4.6,
    reviews: 900,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "104",
    slug: "ifttt",
    name: "IFTTT",
    category: "Productivity & Automation",
    rank: 4,
    logo: "/logos/ifttt.svg",
    tagline: "Automation simple If This Then That",
    description: "IFTTT automatise tâches simples et appareils IoT.",
    features: ["Simple", "IoT support", "Mobile", "Free + Pro"],
    pricing: "Free + $3.99/mois",
    website: "https://ifttt.com",
    rating: 4.4,
    reviews: 800,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "105",
    slug: "microsoft-power-automate",
    name: "Microsoft Power Automate",
    category: "Productivity & Automation",
    rank: 5,
    logo: "/logos/microsoft-power-automate.svg",
    tagline: "Automation Microsoft enterprise",
    description: "Power Automate automatise workflows dans l'écosystème Microsoft.",
    features: ["Office 365 integration", "Cloud flows", "Desktop RPA", "Powerful"],
    pricing: "$15+/mois",
    website: "https://powerautomate.com",
    rating: 4.5,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "106",
    slug: "automation-anywhere",
    name: "Automation Anywhere",
    category: "Productivity & Automation",
    rank: 6,
    logo: "/logos/automation-anywhere.svg",
    tagline: "Enterprise RPA platform",
    description: "Automation Anywhere automatise les processus métier.",
    features: ["RPA", "Enterprise", "AI-powered", "Secure"],
    pricing: "$$$",
    website: "https://automationanywhere.com",
    rating: 4.3,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "107",
    slug: "uipath",
    name: "UiPath",
    category: "Productivity & Automation",
    rank: 7,
    logo: "/logos/uipath.svg",
    tagline: "RPA leader du marché",
    description: "UiPath est leader en RPA pour entreprise.",
    features: ["RPA leader", "AI", "Enterprise", "Cloud/On-prem"],
    pricing: "$$$",
    website: "https://uipath.com",
    rating: 4.4,
    reviews: 900,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "108",
    slug: "blue-prism",
    name: "Blue Prism",
    category: "Productivity & Automation",
    rank: 8,
    logo: "/logos/blue-prism.svg",
    tagline: "RPA intelligent automation",
    description: "Blue Prism combine RPA et intelligent automation.",
    features: ["RPA platform", "AI", "Cloud-ready", "Enterprise"],
    pricing: "$$$",
    website: "https://blueprism.com",
    rating: 4.2,
    reviews: 520,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "109",
    slug: "workato",
    name: "Workato",
    category: "Productivity & Automation",
    rank: 9,
    logo: "/logos/workato.svg",
    tagline: "Integration + automation cloud",
    description: "Workato combine intégration et automation.",
    features: ["1000+ connectors", "Cloud native", "Powerful", "AI assist"],
    pricing: "$25+/mois",
    website: "https://workato.com",
    rating: 4.3,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "110",
    slug: "tray-io",
    name: "Tray.io",
    category: "Productivity & Automation",
    rank: 10,
    logo: "/logos/tray-io.svg",
    tagline: "iPaaS integration platform",
    description: "Tray.io intègre et automatise applications.",
    features: ["Integration platform", "Workflows", "API", "Enterprise"],
    pricing: "Custom pricing",
    website: "https://tray.io",
    rating: 4.1,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 7. AI CODE & DEVELOPMENT
  // ============================================
  {
    id: "121",
    slug: "cursor",
    name: "Cursor",
    category: "AI Code & Development",
    rank: 1,
    logo: "/logos/cursor.svg",
    tagline: "IDE IA pour développeurs",
    description: "Cursor est l'IDE le plus avancé avec IA pour coder plus vite.",
    features: ["Chat IA", "Code generation", "VS Code base", "Native codebase"],
    pricing: "Free + $20/mois",
    website: "https://cursor.com",
    rating: 4.9,
    reviews: 1400,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "122",
    slug: "github-copilot",
    name: "GitHub Copilot",
    category: "AI Code & Development",
    rank: 2,
    logo: "/logos/github-copilot.svg",
    tagline: "AI pair programmer OpenAI",
    description: "GitHub Copilot assiste la programmation avec AI en temps réel.",
    features: ["Code completion", "Fast", "Multi-language", "VS Code + more"],
    pricing: "$10/mois",
    website: "https://github.com/features/copilot",
    rating: 4.8,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "123",
    slug: "claude-code",
    name: "Claude Code",
    category: "AI Code & Development",
    rank: 3,
    logo: "/logos/claude-code.svg",
    tagline: "Code generation avec Claude",
    description: "Claude Code génère et explique du code précis.",
    features: ["Code generation", "Explanations", "Debugging", "Multi-language"],
    pricing: "Free + $20/mois",
    website: "https://claude.ai",
    rating: 4.7,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "124",
    slug: "codeium",
    name: "Codeium",
    category: "AI Code & Development",
    rank: 4,
    logo: "/logos/codeium.svg",
    tagline: "Copilot gratuit",
    description: "Codeium offre code completion IA gratuitement.",
    features: ["Gratuit", "Code completion", "Multi-IDE", "Fast"],
    pricing: "Free",
    website: "https://codeium.com",
    rating: 4.6,
    reviews: 1000,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "125",
    slug: "tabnine",
    name: "Tabnine",
    category: "AI Code & Development",
    rank: 5,
    logo: "/logos/tabnine.svg",
    tagline: "Code completion IA",
    description: "Tabnine fournit code completion intelligent.",
    features: ["Code completion", "Multi-IDE", "Privacy-focused", "Offline"],
    pricing: "Free + $12/mois",
    website: "https://tabnine.com",
    rating: 4.5,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "126",
    slug: "replit",
    name: "Replit with AI",
    category: "AI Code & Development",
    rank: 6,
    logo: "/logos/replit.svg",
    tagline: "IDE cloud avec IA",
    description: "Replit est un IDE cloud avec assistant IA.",
    features: ["Cloud IDE", "AI assist", "Collaboration", "Deploy"],
    pricing: "Free + $7/mois",
    website: "https://replit.com",
    rating: 4.4,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "127",
    slug: "hugging-face",
    name: "Hugging Face",
    category: "AI Code & Development",
    rank: 7,
    logo: "/logos/hugging-face.svg",
    tagline: "Modèles IA pour développeurs",
    description: "Hugging Face fournit modèles et outils IA open-source.",
    features: ["Model hub", "Transformers lib", "Spaces", "Datasets"],
    pricing: "Free + $",
    website: "https://huggingface.co",
    rating: 4.6,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "128",
    slug: "vscode-ai",
    name: "VS Code + AI Extensions",
    category: "AI Code & Development",
    rank: 8,
    logo: "/logos/vscode-ai.svg",
    tagline: "VS Code avec extensions IA",
    description: "VS Code avec extensions IA pour coding amélioré.",
    features: ["Extensible", "Many AI options", "Popular", "Free"],
    pricing: "Free",
    website: "https://code.visualstudio.com",
    rating: 4.7,
    reviews: 1400,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "129",
    slug: "jetbrains-ai",
    name: "JetBrains with AI Assistant",
    category: "AI Code & Development",
    rank: 9,
    logo: "/logos/jetbrains-ai.svg",
    tagline: "IDEs JetBrains avec AI",
    description: "JetBrains IDEs incluent AI Assistant.",
    features: ["All IDEs", "Smart completion", "Refactoring", "Explain code"],
    pricing: "$20+/mois",
    website: "https://jetbrains.com",
    rating: 4.5,
    reviews: 950,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "130",
    slug: "phind",
    name: "Phind",
    category: "AI Code & Development",
    rank: 10,
    logo: "/logos/phind.svg",
    tagline: "Search engine pour coding",
    description: "Phind est un search engine spécialisé pour programmeurs.",
    features: ["Code search", "AI answers", "Documentation", "Free"],
    pricing: "Free",
    website: "https://phind.com",
    rating: 4.2,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 8. HR & RECRUITMENT
  // ============================================
  {
    id: "141",
    slug: "lever",
    name: "Lever",
    category: "HR & Recruitment",
    rank: 1,
    logo: "/logos/lever.svg",
    tagline: "ATS avec IA pour recrutement",
    description: "Lever est un ATS moderne utilisant l'IA pour recrutement.",
    features: ["AI resume parsing", "Candidate matching", "Collaboration", "Scalable"],
    pricing: "$",
    website: "https://lever.co",
    rating: 4.7,
    reviews: 980,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "142",
    slug: "greenhouse",
    name: "Greenhouse",
    category: "HR & Recruitment",
    rank: 2,
    logo: "/logos/greenhouse.svg",
    tagline: "Recrutement talent avec IA",
    description: "Greenhouse utilise l'IA pour optimiser le recrutement.",
    features: ["AI sourcing", "Interview kit", "Candidate tracking", "Analytics"],
    pricing: "$",
    website: "https://greenhouse.io",
    rating: 4.6,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "143",
    slug: "workable",
    name: "Workable",
    category: "HR & Recruitment",
    rank: 3,
    logo: "/logos/workable.svg",
    tagline: "ATS abordable avec IA",
    description: "Workable propose un ATS abordable avec fonctionnalités IA.",
    features: ["AI screening", "Job posting", "Candidate matching", "Affordable"],
    pricing: "$",
    website: "https://workable.com",
    rating: 4.5,
    reviews: 920,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "144",
    slug: "bamboohr",
    name: "BambooHR",
    category: "HR & Recruitment",
    rank: 4,
    logo: "/logos/bamboohr.svg",
    tagline: "SIRH avec recrutement IA",
    description: "BambooHR combine SIRH et recrutement avec IA.",
    features: ["Recrutement IA", "SIRH", "Onboarding", "HR analytics"],
    pricing: "$",
    website: "https://bamboohr.com",
    rating: 4.4,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "145",
    slug: "ashby",
    name: "Ashby",
    category: "HR & Recruitment",
    rank: 5,
    logo: "/logos/ashby.svg",
    tagline: "ATS moderne et performant",
    description: "Ashby est un ATS moderne avec IA intégrée.",
    features: ["Modern interface", "AI tools", "Collaboration", "API"],
    pricing: "$",
    website: "https://ashby.ai",
    rating: 4.6,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "146",
    slug: "manpower-group",
    name: "ManpowerGroup Solutions",
    category: "HR & Recruitment",
    rank: 6,
    logo: "/logos/manpower-group.svg",
    tagline: "Staffing avec IA",
    description: "ManpowerGroup utilise l'IA pour matching talents.",
    features: ["AI matching", "Staffing", "Contingent labor", "Global"],
    pricing: "Custom",
    website: "https://manpowergroup.com",
    rating: 4.2,
    reviews: 520,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "147",
    slug: "sapdayforce",
    name: "SAP SuccessFactors",
    category: "HR & Recruitment",
    rank: 7,
    logo: "/logos/sapdayforce.svg",
    tagline: "SIRH enterprise SAP",
    description: "SAP SuccessFactors est une solution SIRH avec IA.",
    features: ["Recrutement IA", "SIRH enterprise", "Analytics", "Global"],
    pricing: "$$$",
    website: "https://sap.com/products/hcm",
    rating: 4.3,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "148",
    slug: "talentwise",
    name: "TalentWise",
    category: "HR & Recruitment",
    rank: 8,
    logo: "/logos/talentwise.svg",
    tagline: "Video screening avec IA",
    description: "TalentWise automatise présélection vidéo avec IA.",
    features: ["Video screening", "AI assessment", "Bias reduction", "Scalable"],
    pricing: "$",
    website: "https://talentwise.co",
    rating: 4.2,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "149",
    slug: "pymetrics",
    name: "Pymetrics",
    category: "HR & Recruitment",
    rank: 9,
    logo: "/logos/pymetrics.svg",
    tagline: "Neuroscience + AI recrutement",
    description: "Pymetrics utilise neuroscience et IA pour évaluation talents.",
    features: ["Neuroscience games", "AI assessment", "Bias-free", "Fair"],
    pricing: "$",
    website: "https://pymetrics.com",
    rating: 4.1,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "150",
    slug: "employbl",
    name: "Employbl",
    category: "HR & Recruitment",
    rank: 10,
    logo: "/logos/employbl.svg",
    tagline: "Job board avec IA",
    description: "Employbl est un job board utilisant l'IA pour matching.",
    features: ["AI matching", "Job board", "Affordable", "Simple"],
    pricing: "$",
    website: "https://employbl.com",
    rating: 3.9,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 9. MARKETING & SEO
  // ============================================
  {
    id: "161",
    slug: "semrush",
    name: "Semrush",
    category: "Marketing & SEO",
    rank: 1,
    logo: "/logos/semrush.svg",
    tagline: "Suite SEO complète avec IA",
    description: "Semrush est la suite SEO leader avec IA intégrée.",
    features: ["Keyword research", "Backlink analysis", "AI content", "Competitive intel"],
    pricing: "$99+/mois",
    website: "https://semrush.com",
    rating: 4.8,
    reviews: 1500,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "162",
    slug: "ahrefs",
    name: "Ahrefs",
    category: "Marketing & SEO",
    rank: 2,
    logo: "/logos/ahrefs.svg",
    tagline: "Backlink analysis et SEO",
    description: "Ahrefs excelle dans l'analyse backlinks et SEO.",
    features: ["Backlink database", "Keyword research", "Content explorer", "Rank tracker"],
    pricing: "$99+/mois",
    website: "https://ahrefs.com",
    rating: 4.7,
    reviews: 1300,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "163",
    slug: "moz",
    name: "Moz",
    category: "Marketing & SEO",
    rank: 3,
    logo: "/logos/moz.svg",
    tagline: "SEO tools avec IA",
    description: "Moz propose suite SEO complète avec IA.",
    features: ["Keyword research", "Rank tracking", "Site audit", "Affordable"],
    pricing: "$79+/mois",
    website: "https://moz.com",
    rating: 4.6,
    reviews: 1100,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "164",
    slug: "hubspot",
    name: "HubSpot",
    category: "Marketing & SEO",
    rank: 4,
    logo: "/logos/hubspot.svg",
    tagline: "Marketing platform avec IA",
    description: "HubSpot est plateforme marketing complète avec IA.",
    features: ["Email marketing", "CRM", "Automation", "Analytics"],
    pricing: "Free + $",
    website: "https://hubspot.com",
    rating: 4.7,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "165",
    slug: "surfer",
    name: "Surfer",
    category: "Marketing & SEO",
    rank: 5,
    logo: "/logos/surfer.svg",
    tagline: "SEO content optimization IA",
    description: "Surfer optimise contenu pour SEO avec IA.",
    features: ["Content optimization", "AI writing", "Keyword guidance", "Rank tracking"],
    pricing: "$79+/mois",
    website: "https://surfer.com",
    rating: 4.5,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "166",
    slug: "jasper-seo",
    name: "Jasper for SEO",
    category: "Marketing & SEO",
    rank: 6,
    logo: "/logos/jasper-seo.svg",
    tagline: "Contenu SEO avec IA",
    description: "Jasper génère contenu optimisé SEO avec IA.",
    features: ["AI writing", "SEO templates", "Multi-language", "Brand voice"],
    pricing: "$39+/mois",
    website: "https://jasper.ai",
    rating: 4.4,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "167",
    slug: "copysmith",
    name: "Copysmith",
    category: "Marketing & SEO",
    rank: 7,
    logo: "/logos/copysmith.svg",
    tagline: "Copy marketing IA",
    description: "Copysmith génère copy marketing avec IA.",
    features: ["Marketing copy", "Product descriptions", "Email templates"],
    pricing: "$19+/mois",
    website: "https://copysmith.com",
    rating: 4.2,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "168",
    slug: "adobe-sensei",
    name: "Adobe Sensei",
    category: "Marketing & SEO",
    rank: 8,
    logo: "/logos/adobe-sensei.svg",
    tagline: "IA for marketing creative",
    description: "Adobe Sensei aide dans création contenu marketing.",
    features: ["Image analysis", "Optimization", "Personalization", "In Adobe apps"],
    pricing: "$",
    website: "https://adobe.com/sensei",
    rating: 4.3,
    reviews: 650,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "169",
    slug: "outbrain",
    name: "Outbrain",
    category: "Marketing & SEO",
    rank: 9,
    logo: "/logos/outbrain.svg",
    tagline: "Content discovery avec IA",
    description: "Outbrain distribue contenu avec IA.",
    features: ["Content distribution", "AI targeting", "Analytics", "Global reach"],
    pricing: "CPC/CPM model",
    website: "https://outbrain.com",
    rating: 4.1,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "170",
    slug: "brandwatch",
    name: "Brandwatch",
    category: "Marketing & SEO",
    rank: 10,
    logo: "/logos/brandwatch.svg",
    tagline: "Consumer intelligence avec IA",
    description: "Brandwatch utilise IA pour comprendre consommateurs.",
    features: ["Social listening", "Sentiment analysis", "Consumer insights", "Real-time"],
    pricing: "$",
    website: "https://brandwatch.com",
    rating: 3.9,
    reviews: 510,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },

  // ============================================
  // 10. SALES & CRM
  // ============================================
  {
    id: "181",
    slug: "salesforce",
    name: "Salesforce with Einstein AI",
    category: "Sales & CRM",
    rank: 1,
    logo: "/logos/salesforce.svg",
    tagline: "CRM leader avec IA Einstein",
    description: "Salesforce est le leader CRM avec Einstein AI intégrée.",
    features: ["Einstein AI", "Predictive analytics", "Automation", "Enterprise scale"],
    pricing: "$165+/user/mois",
    website: "https://salesforce.com",
    rating: 4.7,
    reviews: 1800,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "182",
    slug: "hubspot-crm",
    name: "HubSpot CRM",
    category: "Sales & CRM",
    rank: 2,
    logo: "/logos/hubspot-crm.svg",
    tagline: "CRM gratuit puis payant",
    description: "HubSpot CRM offre solution CRM avec IA accessible.",
    features: ["Gratuit tier", "AI insights", "Sales automation", "Easy"],
    pricing: "Free + $",
    website: "https://hubspot.com/products/crm",
    rating: 4.8,
    reviews: 1600,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "183",
    slug: "pipedrive",
    name: "Pipedrive",
    category: "Sales & CRM",
    rank: 3,
    logo: "/logos/pipedrive.svg",
    tagline: "CRM sales-focused avec IA",
    description: "Pipedrive est CRM focalisé sales avec IA.",
    features: ["Sales focus", "Pipeline management", "AI insights", "Affordable"],
    pricing: "$24.90+/user/mois",
    website: "https://pipedrive.com",
    rating: 4.6,
    reviews: 1200,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "184",
    slug: "zoho-crm",
    name: "Zoho CRM",
    category: "Sales & CRM",
    rank: 4,
    logo: "/logos/zoho-crm.svg",
    tagline: "CRM abordable avec IA",
    description: "Zoho CRM propose CRM abordable avec IA.",
    features: ["AI-powered", "Sales automation", "Lead management", "Very affordable"],
    pricing: "$14+/user/mois",
    website: "https://zoho.com/crm",
    rating: 4.5,
    reviews: 1000,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "185",
    slug: "copper",
    name: "Copper",
    category: "Sales & CRM",
    rank: 5,
    logo: "/logos/copper.svg",
    tagline: "CRM integré à Gmail",
    description: "Copper intègre CRM directement dans Gmail avec IA.",
    features: ["Gmail integration", "No manual entry", "AI insights", "Simple"],
    pricing: "$25+/user/mois",
    website: "https://copper.com",
    rating: 4.4,
    reviews: 850,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "186",
    slug: "freshsales",
    name: "Freshsales",
    category: "Sales & CRM",
    rank: 6,
    logo: "/logos/freshsales.svg",
    tagline: "CRM moderne avec IA",
    description: "Freshsales est CRM moderne avec IA.",
    features: ["AI insights", "Sales automation", "Territory management", "Affordable"],
    pricing: "$29+/user/mois",
    website: "https://freshsales.com",
    rating: 4.3,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  },
  {
    id: "187",
    slug: "microsoft-dynamics",
    name: "Microsoft Dynamics 365",
    category: "Sales & CRM",
    rank: 7,
    logo: "/logos/microsoft-dynamics.svg",
    tagline: "CRM enterprise Microsoft",
    description: "Microsoft Dynamics 365 est CRM enterprise avec IA.",
    features: ["Enterprise", "Office integration", "AI copilot", "Powerful"],
    pricing: "$165+/user/mois",
    website: "https://microsoft.com/dynamics",
    rating: 4.2,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop"
  },
  {
    id: "188",
    slug: "oracle-crm",
    name: "Oracle NetSuite CRM",
    category: "Sales & CRM",
    rank: 8,
    logo: "/logos/oracle-crm.svg",
    tagline: "CRM cloud Oracle",
    description: "Oracle NetSuite offre CRM cloud avec IA.",
    features: ["Cloud CRM", "ERP integration", "AI", "Enterprise"],
    pricing: "Custom",
    website: "https://oracle.com/crm",
    rating: 4.1,
    reviews: 520,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    id: "189",
    slug: "agile-crm",
    name: "Agile CRM",
    category: "Sales & CRM",
    rank: 9,
    logo: "/logos/agile-crm.svg",
    tagline: "CRM avec AI pour small business",
    description: "Agile CRM pour small business avec IA.",
    features: ["Small business", "AI scoring", "Automation", "Affordable"],
    pricing: "$9.99+/user/mois",
    website: "https://agilecrm.com",
    rating: 3.9,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1620712014215-7b16992e4e41?w=1200&h=600&fit=crop"
  },
  {
    id: "190",
    slug: "capsule-crm",
    name: "Capsule CRM",
    category: "Sales & CRM",
    rank: 10,
    logo: "/logos/capsule-crm.svg",
    tagline: "CRM simple pour teams",
    description: "Capsule CRM simplifie gestion sales.",
    features: ["Simple", "Small team", "Affordable", "Clean interface"],
    pricing: "$18+/user/mois",
    website: "https://capsulecrm.com",
    rating: 3.8,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop"
  }
];

export const SITE_NAME = "EssentialAI";
export const SITE_DESCRIPTION =
  "Essential AI tools for enterprise — curated Top 10 rankings across security, productivity, sales, marketing and more.";
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://aisecuritypulse.com";

export function getAllTools(): Tool[] {
  return [...tools].sort(
    (a, b) => a.rank - b.rank || a.name.localeCompare(b.name)
  );
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools
    .filter((tool) => tool.category.toLowerCase() === category.toLowerCase())
    .sort((a, b) => a.rank - b.rank);
}

export function searchTools(query: string): Tool[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return tools.filter((tool) => {
    const haystack = [
      tool.name,
      tool.tagline,
      tool.description,
      tool.category,
      tool.pricing,
      ...tool.features,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
}

export function getRelatedTools(tool: Tool, limit = 3): Tool[] {
  return getToolsByCategory(tool.category)
    .filter((t) => t.slug !== tool.slug)
    .slice(0, limit);
}